expense/urls.py
from django.urls import path

from . import views

app_name = "expense"
urlpatterns = [
    path("", views.index, name="index"),
    path("add_expense", views.add_expense, name="add_expense"),
    path("remove_expense/<int:expense_id>", views.remove_expense, name="remove_expense"),
    path("update_expense/<int:expense_id>", views.update_expense, name="update_expense"),
    path("calculate", views.calculate, name="calculate"),
    path("export", views.export, name="export"),
]

expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('expense.urls')),
    path('admin/', admin.site.urls),
]

expense/models.py
from django.db import models

class Expense(models.Model):
    expense = models.CharField(max_length=60)
    price = models.FloatField()

expense/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpRequest, HttpResponseRedirect, QueryDict, HttpResponse
from django.urls import reverse
from django.core.exceptions import BadRequest
import csv
import io

from .models import Expense


def index(request: HttpRequest):
    expenses = Expense.objects.all()
    lost = request.GET.get("lost")
    return render(request, "expense/index.html", {"expenses": expenses, "lost": lost})


def add_expense(request: HttpRequest):
    new_expense = request.POST.get("expense")
    price = request.POST.get("price")
    if price is None or new_expense is None:
        raise BadRequest("did not get expected fields")

    try:
        price = float(price)
    except Exception:
        raise BadRequest("invalid price")

    if price <= 0:
        raise BadRequest("price is less than or equal to zero")
    if new_expense.strip() == "":
        raise BadRequest("expense is empty")
    new_expense = Expense(expense=new_expense, price=price)
    new_expense.save()
    return HttpResponseRedirect(reverse("expense:index"))


def remove_expense(request: HttpRequest, expense_id: int):
    expense = get_object_or_404(Expense, id=expense_id)
    expense.delete()
    return HttpResponseRedirect(reverse("expense:index"))


def update_expense(request: HttpRequest, expense_id: int):
    expense = get_object_or_404(Expense, id=expense_id)
    data = QueryDict(request.body)

    price = data.get("price")
    new_expense = data.get("expense")
    if price == "" and new_expense == "":
        return HttpResponseRedirect(reverse("expense:index"))

    try:
        if price != "":
            price = float(price)
    except Exception:
        raise BadRequest("invalid price")

    if price != "" and price <= 0:
        raise BadRequest("price is smaller than or equal to zero")

    if new_expense != "" and new_expense.strip() == "":
        raise BadRequest("expense is empty")

    if price != "":
        expense.price = price
    if new_expense != "":
        expense.expense = new_expense
    expense.save()
    return HttpResponseRedirect(reverse("expense:index"))


def calculate(request: HttpRequest):
    expenses = get_list_or_404(Expense)
    prices = []
    for expense in expenses:
        prices.append(expense.price)
    lost = sum(prices)
    target_url = f"{reverse('expense:index')}?lost={lost}"
    return HttpResponseRedirect(target_url)


def export(request: HttpRequest):
    expenses = get_list_or_404(Expense)
    headers = ["expense", "price"]
    rows = []
    for expense in expenses:
        rows.append([expense.expense, expense.price])

    output_buffer = io.StringIO()
    writer = csv.writer(output_buffer)
    writer.writerow(headers)
    writer.writerows(rows)

    csv_content = output_buffer.getvalue()
    output_buffer.close()
    response = HttpResponse(csv_content, content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="expenses.csv"'
    return response

expense/templates/expense/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.6/dist/htmx.min.js"></script>
        <script src="https://cdn.tailwindcss.com"></script>
        <title>Expenses</title>
    </head>
    <body class="Geist bg-[#18181b]" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <h1 class="font-bold text-center text-4xl mb-3 mt-3 text-white">Expense Tracker</h1>
        <div class="flex justify-center">
            <form hx-post="{% url 'expense:add_expense' %}" hx-swap="outerHTML" hx-target="body">
            {% csrf_token %}
                <input class="p-3 border border-[#3f3f46] rounded-md text-center pl-10 pr-10 mb-3 bg-[#27272a] text-gray-400 text-base focus:outline-none focus:ring-0" type="text" placeholder="add expense" name="expense">
                <input class="p-3 border border-[#3f3f46] rounded-md text-center pl-0 pr-0 mb-3 bg-[#27272a] text-gray-400 text-base focus:outline-none focus:ring-0" type="text" placeholder="add price" name="price">
                <button class="p-3 border border-[#fef08a] rounded-md text-center mb-3 bg-[#fef08a]" type="submit">add</button>
            </form>
        </div>
        <div class="flex justify-center">
            {% if expenses %}
                <ul>
                    {% for expense in expenses %}
                    <li>
                        <div class="flex flex-row space-x-5">
                            <p class="text-2xl mb-2 text-white font-semibold">{{ expense.expense }}</p> 
                            <p class="text-2xl mb-2 text-green-400 font-semibold">${{ expense.price }}</p>
                        </div>
                        <form hx-put="{% url 'expense:update_expense' expense.id %}" hx-swap="outerHTML" hx-target="body">
                            <input class="p-1 border border-[#3f3f46] rounded-md text-center mb-3 bg-[#27272a] text-gray-400 text-base focus:outline-none focus:ring-0" type="text" placeholder="update expense" name="expense">
                            <input class="p-1 border border-[#3f3f46] rounded-md text-center mb-3 bg-[#27272a] text-gray-400 text-base focus:outline-none focus:ring-0" type="text" placeholder="update price" name="price">
                            <button class="bg-blue-500 border border-blue-600 rounded-md p-1 text-center mb-3 font-semibold" type="submit">🖉 edit</button>
                        </form>
                        <button class="bg-rose-500 border border-rose-600 rounded-md p-1 text-center mb-5 font-semibold" hx-delete="{% url 'expense:remove_expense' expense.id %}" hx-swap="outerHTML" hx-target="body" type="submit">delete</button>
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="text-sm mb-5 mt-1 text-gray-400">your list is empty</p>
            {% endif %}
        </div>
        <div class="flex justify-center flex-row space-x-5">
            <a class="bg-green-500 border border-green-600 rounded-md p-3 text-center mb-5 font-semibold duration-200 transition-all hover:bg-green-400 hover:border-green-500" type="button" href="{% url 'expense:export' %}">🖺 Export</a>
            <button class="bg-amber-400 border border-amber-500 rounded-md p-3 text-center mb-5 font-semibold duration-200 transition-all hover:bg-amber-300 hover:border-amber-400" hx-get="{% url 'expense:calculate' %}" hx-swap="outerHTML" hx-target="body">⨸ Calculate</button>
        </div>
        {% if lost %}
            <p class="text-rose-500 text-center font-bold text-2xl">You Lost: ${{ lost }}</p>
        {% endif %}
    </body>
</html>